platform :ios, '9.0'

use_frameworks!

target 'GradientProgressBar_Example' do
  pod 'GradientProgressBar', :path => '../'

  target 'GradientProgressBar_Tests' do
    inherit! :search_paths

  end
end
